spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hs_dzbb?currentSchema=user_service&user=hp&password=SFgIgwXeJD5QNWpFcMLDaVvL5BFANp0K
    username: hp
    password: SFgIgwXeJD5QNWpFcMLDaVvL5BFANp0K

#  data:
#    redis:
#      port: 26379
#      password:
#      sentinel:
#        master: mymaster
#        nodes: localhost
#
#  cache:
#    type: redis
#    redis:
#      cache-null-values: false
#      time-to-live: 300000

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: authentication-service
          uri: http://localhost:8684
          metadata:
            public: true
            docs: /api/docs
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/?(?<segment>.*), /auth/$\{segment}
        - id: user-service
          uri: http://localhost:8688
          metadata:
            public: true
            docs: /api/docs
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/?(?<segment>.*), /user/$\{segment}
        - id: doctor-service
          uri: http://localhost:8690
          metadata:
            public: true
            docs: /api/docs
          predicates:
            - Path=/api/doctor/**
          filters:
            - RewritePath=/api/doctor/?(?<segment>.*), /doctor/$\{segment}
        - id: medicine-service
          uri: http://localhost:8692
          metadata:
            public: true
            docs: /api/docs
          predicates:
            - Path=/api/medicine/**
          filters:
            - RewritePath=/api/medicine/?(?<segment>.*), /medicine/$\{segment}

