spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hs_dzbb?currentSchema=user_service&user=hp&password=SFgIgwXeJD5QNWpFcMLDaVvL5BFANp0K
    username: hp
    password: SFgIgwXeJD5QNWpFcMLDaVvL5BFANp0K

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: authentication-service
          uri: http://localhost:8684
          predicates:
            - Path=/api/auth/**
          filters:
#            - RewritePath=/api/auth/(?<segment>.*), /auth/${segment}
            - SetPath=/{path}
        - id: user-service
          uri: http://localhost:8688
          predicates:
            - Path=/api/user/**
          filters:
#            - RewritePath=/api/user/(?<segment>.*), /user/${segment}
            - SetPath=/{path}
        - id: doctor-service
          uri: http://localhost:8690
          predicates:
            - Path=/api/doctor/**
          filters:
#            - RewritePath=/api/doctor/(?<segment>.*), /doctor/${segment}
            - SetPath=/{path}
        - id: medicine-service
          uri: http://localhost:8692
          predicates:
            - Path=/api/medicine/**
          filters:
#            - RewritePath=/api/medicine/(?<segment>.*), /medicine/${segment}
            - SetPath=/{path}  # No modification, forward the entire path

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: http://localhost:8684/v3/api-docs
        name: Auth Service
        primaryName: Auth Service
      - url: http://localhost:8688/v3/api-docs
        name: User Service
        primaryName: User Service
      - url: http://localhost:8690/v3/api-docs
        name: Doctor Service
        primaryName: Doctor Service
      - url: http://localhost:8692/v3/api-docs
        name: Medicine Service
        primaryName: Medicine Service
