spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/hs_dzbb?currentSchema=user_service&user=hp&password=SFgIgwXeJD5QNWpFcMLDaVvL5BFANp0K
    username: hp
    password: SFgIgwXeJD5QNWpFcMLDaVvL5BFANp0K

#  data:
#    redis:
#      port: 26379
#      password:
#      sentinel:
#        master: mymaster
#        nodes: localhost
#
#  cache:
#    type: redis
#    redis:
#      cache-null-values: false
#      time-to-live: 300000

  cloud:
      gateway:
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
        routes:
          - id: authentication-service
            uri: ${AUTH_SERVICE_URL_DOCKER_LOCAL}
            metadata:
              public: true
              docs: /api/docs
            predicates:
              - Path=/api/auth/**
            filters:
              - RewritePath=/api/auth/?(?<segment>.*), /auth/$\{segment}
          - id: user-service
            uri: ${USER_SERVICE_URL_DOCKER_LOCAL}
            metadata:
              public: true
              docs: /api/docs
            predicates:
              - Path=/api/user/**
            filters:
              - RewritePath=/api/user/?(?<segment>.*), /user/$\{segment}
          - id: doctor-service
            uri: ${DOCTOR_SERVICE_URL_DOCKER_LOCAL}
            metadata:
              public: true
              docs: /api/docs
            predicates:
              - Path=/api/doctor/**
            filters:
              - RewritePath=/api/doctor/?(?<segment>.*), /doctor/$\{segment}
          - id: medicine-service
            uri: ${MEDICINE_SERVICE_URL_DOCKER_LOCAL}
            metadata:
              public: true
              docs: /api/docs
            predicates:
              - Path=/api/medicine/**
            filters:
              - RewritePath=/api/medicine/?(?<segment>.*), /medicine/$\{segment}

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: ${AUTH_SERVICE_URL_DOCKER_LOCAL}/v3/api-docs
        name: Auth Service
        primaryName: Auth Service
      - url: ${USER_SERVICE_URL_DOCKER_LOCAL}/v3/api-docs
        name: User Service
        primaryName: User Service
      - url: ${DOCTOR_SERVICE_URL_DOCKER_LOCAL}/v3/api-docs
        name: Doctor Service
        primaryName: Doctor Service
      - url: ${MEDICINE_SERVICE_URL_DOCKER_LOCAL}/v3/api-docs
        name: Medicine Service
        primaryName: Medicine Service
