spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hs_dzbb?currentSchema=user_service
    username: hp
    password: SFgIgwXeJD5QNWpFcMLDaVvL5BFANp0K

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: authentication-service
          uri: http://localhost:8684
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1 # Removes /api from the path
          metadata:
            public: true

        - id: user-service
          uri: http://localhost:8688
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1 # Removes /api from the path
          metadata:
            public: true

        - id: doctor-service
          uri: http://localhost:8690
          predicates:
            - Path=/api/doctor/**
          filters:
            - StripPrefix=1 # Removes /api from the path
          metadata:
            public: true

        - id: medicine-service
          uri: http://localhost:8692
          predicates:
            - Path=/api/medicine/**
          filters:
            - StripPrefix=2 # Removes /api from the path
          metadata:
            public: true

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: http://localhost:8684/v3/api-docs
        name: Auth Service
        primaryName: Auth Service
      - url: http://localhost:8688/v3/api-docs
        name: User Service
        primaryName: User Service
      - url: http://localhost:8690/v3/api-docs
        name: Doctor Service
        primaryName: Doctor Service
      - url: https://singularly-holy-aphid.ngrok-free.app/api/medicine/v3/api-docs
        name: Medicine Service
